export const ACTION_ASYNC_APP = {
    INIT_USER_INFO: 'ACTION_ASYNC_APP_INIT_USER_INFO',
    INIT_PATIENT_ALL: 'ACTION_ASYNC_APP_INIT_PATIENT_ALL',
    ACTIVE_CONF_LOG: 'ACTION_ASYNC_APP_ACTIVE_CONF_LOG',
    CON_CONF: 'ACTION_ASYNC_APP_CON_CONF',
    CONF_SESSION: 'ACTION_ASYNC_APP_CONF_SESSION',

};
